CREATE TABLE projects (
ID INT(11) AUTO_INCREMENT UNIQUE,
TITEL VARCHAR(255),
NEWS VARCHAR(5000),
CREATED_AT VARCHAR(255),
FILENAME VARCHAR(100),
LINK VARCHAR(255)
);


CREATE TABLE accounts (
    ID INT(11) AUTO_INCREMENT UNIQUE,
    USERNAME VARCHAR(255) UNIQUE,
    PASSWORD VARCHAR(255),
    CREATED_AT VARCHAR(255),
    EMAIL VARCHAR(255),
    TOKEN VARCHAR(255)
)
